# Generic docker-compose setup for php laravel development.
# Author umurkaragoz
# Version 1.1.5

version: '3'

services:
  web:
    container_name: ${APP_NAME}
    build: .
    ports:
      - ${HTTP_PORT}:80
    working_dir: /var/www
    volumes:
      - .:/var/www/
    networks:
      - team
  memcached:
    image: 'memcached:alpine'
    ports:
      - '11211:11211'
    networks:
      - team
  mariadb:
    container_name: ${APP_NAME}_mariadb
    image: mariadb:10.4
    restart: always
    ports:
      - ${DB_PORT}:3306
    volumes:
      - mariadata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      team:
        aliases:
          - ${DB_HOST}

volumes:
  mariadata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DOCKER_DATA_PATH}\mariadb

networks:
  team:
    driver: bridge
